name: expert_system

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --verbose
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
